src/main/java/com/blogspot/bwgypyth/lotro/model/Packet.java
/*
 * Copyright (c) 2013 bwgypyth
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.blogspot.bwgypyth.lotro.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

@Entity
public class Packet extends OwnedEntity {

	@Column(length = 16777216)
	private String data;
	private String name;
	@ManyToOne(fetch = FetchType.LAZY)
	private PacketGroup group;
	@OneToMany(mappedBy = "packet", cascade = CascadeType.ALL)
	private List<Analysis> analyses = new ArrayList<>(0);

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public PacketGroup getGroup() {
		return group;
	}

	public void setGroup(PacketGroup group) {
		this.group = group;
	}

	public List<Analysis> getAnalyses() {
		return analyses;
	}

	public void setAnalyses(List<Analysis> analyses) {
		this.analyses = analyses;
	}

	@Transient
	public int getAnalysesSize() {
		return analyses != null ? analyses.size() : 0;
	}

}

src/main/java/com/blogspot/bwgypyth/lotro/servlets/PacketAjaxServlet.java
/*
 * Copyright (c) 2013 bwgypyth
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.blogspot.bwgypyth.lotro.servlets;

import java.io.IOException;
import java.nio.channels.NonReadableChannelException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.servlet.ServletOutputStream;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.blogspot.bwgypyth.lotro.EMF;
import com.blogspot.bwgypyth.lotro.logic.AnalysisFactory;
import com.blogspot.bwgypyth.lotro.model.Analysis;
import com.blogspot.bwgypyth.lotro.model.AnalysisEntry;
import com.blogspot.bwgypyth.lotro.model.OwnedEntity;
import com.blogspot.bwgypyth.lotro.model.Packet;
import com.blogspot.bwgypyth.lotro.model.PacketGroup;

@WebServlet(urlPatterns = "/packet_ajax")
public class PacketAjaxServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws IOException {
		switch (req.getParameter("operation")) {
		case "update_packetname":
			resp.getOutputStream().print(updatePacketname(req));
			break;
		case "update_analysisname":
			resp.getOutputStream().print(updateAnalysisname(req));
			break;
		case "create_analysis":
			resp.getOutputStream().print(createAnalysis());
			break;
		case "update_analysisentry":
			resp.getOutputStream().print(updateAnalysisentry(req));
			break;
		case "create_analysisentry":
			resp.getOutputStream().print(createAnalysisentry(req));
			break;
		case "autocomplete_color":
			autocompleteColor(req, resp);
			break;
		case "autocomplete_name":
			autocompleteName(req, resp);
			break;
		case "delete_entry":
			resp.getOutputStream().print(deleteEntry(req));
			break;
		case "delete_analysis":
			resp.getOutputStream().print(deleteAnalysis(req));
			break;
		case "delete_packet":
			resp.getOutputStream().print(deletePacket(req));
			break;
		case "select_group":
			resp.getOutputStream().print(selectGroup(req));
			break;
		case "create_group":
			resp.getOutputStream().print(createGroup(req));
			break;
		default:
			resp.getOutputStream().print("unknown");
			break;
		}
	}

	private static String deleteEntry(HttpServletRequest req) {
		int analysisentryKey = Integer.parseInt(req.getParameter("entry_key"));
		EntityManager em = EMF.get().createEntityManager();
		try {
			em.getTransaction().begin();
			AnalysisEntry analysisEntry = em.find(AnalysisEntry.class, analysisentryKey);
			em.remove(analysisEntry);
			em.getTransaction().commit();
		} finally {
			if (em.getTransaction().isActive()) {
				em.getTransaction().rollback();
			}
			em.close();
		}
		return "ok";
	}

	private static String deleteAnalysis(HttpServletRequest req) {
		int analysisKey = Integer.parseInt(req.getParameter("analysis_key"));
		EntityManager em = EMF.get().createEntityManager();
		try {
			em.getTransaction().begin();
			Analysis analysis = em.find(Analysis.class, analysisKey);
			em.remove(analysis);
			for (AnalysisEntry analysisEntry : analysis.getAnalysisEntries()) {
				em.remove(analysisEntry);
			}

			Packet packet = analysis.getPacket();
			packet.getAnalyses().remove(analysis);
			if (packet.getAnalyses().isEmpty()) {
				Analysis stubAnalysis = AnalysisFactory.createAnalysis(packet);
				OwnedEntity.setModified(packet, "anoynmous");
				em.persist(stubAnalysis);
			}

			em.getTransaction().commit();
		} finally {
			if (em.getTransaction().isActive()) {
				em.getTransaction().rollback();
			}
			em.close();
		}
		return "ok";
	}

	private static String deletePacket(HttpServletRequest req) {
		Integer packetKey = Integer.valueOf(req.getParameter("packet_key"));
		EntityManager em = EMF.get().createEntityManager();
		try {
			em.getTransaction().begin();
			Packet packet = em.find(Packet.class, packetKey);
			em.remove(packet);
			for (Analysis analysis : packet.getAnalyses()) {
				em.remove(analysis);
				for (AnalysisEntry analysisEntry : analysis
						.getAnalysisEntries()) {
					em.remove(analysisEntry);
				}
			}
			em.getTransaction().commit();
		} finally {
			if (em.getTransaction().isActive()) {
				em.getTransaction().rollback();
			}
			em.close();
		}
		return "ok";
	}

	private static void autocompleteColor(HttpServletRequest req,
			HttpServletResponse resp) throws IOException {
		ServletOutputStream out = resp.getOutputStream();
		resp.setContentType("application/json");
		String term = req.getParameter("term");
		EntityManager em = EMF.get().createEntityManager();
		try {
			@SuppressWarnings("unchecked")
			List<String> backgroundColors = em
					.createQuery(
							"select distinct entry.color from AnalysisEntry entry order by entry.color")
					.getResultList();
			Set<String> allColors = new HashSet<>(backgroundColors);

			@SuppressWarnings("unchecked")
			List<String> foregroundColors = em
					.createQuery(
							"select distinct entry.foregroundColor from AnalysisEntry entry where entry.foregroundColor is not null order by entry.foregroundColor")
					.getResultList();
			allColors.addAll(foregroundColors);

			List<String> colors = new ArrayList<>(allColors);
			Collections.sort(colors);
			out.print(getMatchingColors(colors, term));
		} finally {
			em.close();
		}
	}

	private static String getMatchingColors(List<String> colors, String term) {
		StringBuilder buffer = new StringBuilder();
		buffer.append("[");
		for (String color : colors) {
			if (color.startsWith(term)) {
				if (buffer.length() > 1) {
					buffer.append(",");
				}
				buffer.append("{\"id\":\"");
				buffer.append(color);
				buffer.append("\",\"label\":\"<span style=\\\"color: ");
				buffer.append(color);
				buffer.append("\\\">");
				buffer.append(color);
				buffer.append("</span>\",\"value\":\"");
				buffer.append(color);
				buffer.append("\"}");
			}
		}
		buffer.append("]");
		return buffer.toString();
	}

	private static void autocompleteName(HttpServletRequest req,
			HttpServletResponse resp) throws IOException {
		ServletOutputStream out = resp.getOutputStream();
		resp.setContentType("application/json");
		String term = req.getParameter("term");
		EntityManager em = EMF.get().createEntityManager();
		try {
			@SuppressWarnings("unchecked")
			List<String> names = em
					.createQuery(
							"select distinct entry.name from AnalysisEntry entry order by entry.name")
					.getResultList();
			out.print(getMatchingNames(names, term));
		} finally {
			em.close();
		}
	}

	private static String getMatchingNames(List<String> names, String term) {
		StringBuilder buffer = new StringBuilder();
		buffer.append("[");
		for (String name : names) {
			if (name.startsWith(term)) {
				if (buffer.length() > 1) {
					buffer.append(",");
				}
				buffer.append("{\"id\":\"");
				buffer.append(name);
				buffer.append("\",\"label\":\"");
				buffer.append(name);
				buffer.append("\",\"value\":\"");
				buffer.append(name);
				buffer.append("\"}");
			}
		}
		buffer.append("]");
		return buffer.toString();
	}

	private static String createAnalysisentry(HttpServletRequest req) {
		int analysisKey = Integer.parseInt(req.getParameter("analysis_key"));
		int start = Integer.parseInt(
				req.getParameter("entry_start").substring(2), 16);
		int end = Integer.parseInt(req.getParameter("entry_end").substring(2),
				16);
		String description = req.getParameter("entry_description");
		String color = req.getParameter("entry_color").toLowerCase();
		String foregroundColor = req.getParameter("entry_foregroundcolor");
		String name = req.getParameter("entry_name");
		EntityManager em = EMF.get().createEntityManager();
		try {
			em.getTransaction().begin();
			Analysis analysis = em.find(Analysis.class, analysisKey);
			OwnedEntity.setModified(analysis, "anonymous");

			AnalysisEntry analysisEntry = new AnalysisEntry();
			OwnedEntity.setCreated(analysisEntry, "anonymous");
			setAnalysisData(start, end, description, color,
					foregroundColor, name, analysisEntry);
			analysis.getAnalysisEntries().add(analysisEntry);
			analysisEntry.setAnalysis(analysis);

			em.merge(analysis);
			em.getTransaction().commit();
		} finally {
			if (em.getTransaction().isActive()) {
				em.getTransaction().rollback();
			}
			em.close();
		}
		return "ok";
	}

	private static String updateAnalysisentry(HttpServletRequest req) {
		int analysisentryKey = Integer.parseInt(req.getParameter("entry_key"));

		int start = Integer.parseInt(
				req.getParameter("entry_start").substring(2), 16);
		int end = Integer.parseInt(req.getParameter("entry_end").substring(2),
				16);
		String description = req.getParameter("entry_description");
		String color = req.getParameter("entry_color").toLowerCase();

src/main/java/com/blogspot/bwgypyth/lotro/servlets/PacketExportServlet.java
/*
 * Copyright (c) 2013 bwgypyth
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.blogspot.bwgypyth.lotro.servlets;

import java.io.IOException;

import javax.persistence.EntityManager;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.blogspot.bwgypyth.lotro.EMF;
import com.blogspot.bwgypyth.lotro.json.ExportType;
import com.blogspot.bwgypyth.lotro.json.PacketConverter;
import com.blogspot.bwgypyth.lotro.model.Packet;
import org.json.JSONException;

@WebServlet(urlPatterns = "/export/packet")
public class PacketExportServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		if (req.getParameter("packet") == null) {
			throw new ServletException("Missing parameter 'packet'");
		}
		Integer packetKey = Integer.valueOf(req.getParameter("packet"));
		ExportType exportType = "binary".equals(req.getParameter("type")) ? ExportType.BINARY
				: ExportType.JSON;
		EntityManager em = EMF.get().createEntityManager();
		try {
			Packet packet = em.find(Packet.class, packetKey);
			switch (exportType) {
			case JSON:
				resp.setContentType("application/json");
				resp.getOutputStream().print(
						new PacketConverter().toJson(packet).toString());
				break;
			case BINARY:
				resp.setContentType("application/octet-stream");
				String data = packet.getData();
				byte[] hexStringToByteArray = hexStringToByteArray(data);
				resp.getOutputStream().write(hexStringToByteArray);
				break;
			default:
				throw new ServletException("Unknown type " + exportType);
			}
		} catch (JSONException e) {
			throw new ServletException(e.getMessage(), e);
		} finally {
			em.close();
		}
	}

	public static byte[] hexStringToByteArray(String s) {
		int len = s.length();
		byte[] data = new byte[len / 2];
		for (int i = 0; i < len; i += 2) {
			data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4) + Character
					.digit(s.charAt(i + 1), 16));
		}
		return data;
	}
}

src/main/java/com/blogspot/bwgypyth/lotro/servlets/PacketGroupExportServlet.java
package com.blogspot.bwgypyth.lotro.servlets;

import java.io.IOException;

import javax.persistence.EntityManager;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.blogspot.bwgypyth.lotro.EMF;
import com.blogspot.bwgypyth.lotro.json.PacketGroupConverter;
import com.blogspot.bwgypyth.lotro.model.PacketGroup;
import org.json.JSONException;

@WebServlet(urlPatterns = "/export/packetgroup")
public class PacketGroupExportServlet extends HttpServlet {

	private static final long serialVersionUID = -3159504001980261194L;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		if (req.getParameter("group") == null) {
			throw new ServletException("Missing parameter 'group'");
		}
		Integer groupKey = Integer.valueOf(req.getParameter("group"));
		EntityManager em = EMF.get().createEntityManager();
		try {
			PacketGroup group = em.find(PacketGroup.class, groupKey);
			resp.setContentType("application/json");
			resp.getOutputStream().print(
					new PacketGroupConverter().toJson(group).toString());
		} catch (JSONException e) {
			throw new ServletException(e.getMessage(), e);
		} finally {
			em.close();
		}
	}

}

src/main/webapp/navigation.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<nav class="navigation">
	<a href="packets.jsp" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-focus"><span class="ui-button-text">Packets</span></a>
<%
StringBuffer currentUrl = request.getRequestURL();
if (request.getQueryString() != null) {
	currentUrl.append('?').append(request.getQueryString());
}
%>
</nav>

src/main/webapp/packet_import.jsp
<%@page import="com.blogspot.bwgypyth.lotro.model.PacketGroup"%>
<%@page import="java.util.List"%>
<%@page import="com.blogspot.bwgypyth.lotro.EMF"%>
<%@page import="javax.persistence.EntityManager"%>
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%
EntityManager em = EMF.get().createEntityManager();
try {
	List<PacketGroup> groups = em.createQuery("select group from PacketGroup group", PacketGroup.class).getResultList();
%>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title></title>
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script type="text/javascript" src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
		<link rel="stylesheet" href="css/file.css">
	</head>
	<body>
		<%@ include file="navigation.jsp" %>
		<h1>Import packet</h1>
		<form action="/import/packet" method="post">
			<table>
				<tr>
					<th>Group</th>
					<td>
						<select name="group_key" id="group">
<%
	for (PacketGroup group : groups) {
		pageContext.setAttribute("group", group);
%>
							<option value="${group.key}"${group.name == 'Default' ? ' selected="selected"' : ''}>${group.name}</option>
<%
	}
%>
						</select>
						<a onclick="createGroupDialog(); return false;" href="#">Add group</a>
					</td>
				</tr>
				<tr>
					<th>JSON-Data</th>
					<td><textarea rows="10" cols="50" name="packet_data"></textarea></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;"><input type="submit" value="save" /></td>
				</tr>
			</table>
		</form>
		<script type="text/javascript" src="js/group.edit.js"></script>
		<div id="create_group_dialog"></div>
	</body>
</html>
<%
} finally {
	em.close();
}
%>

src/main/webapp/packet_upload.jsp
<%@page import="com.blogspot.bwgypyth.lotro.model.PacketGroup"%>
<%@page import="java.util.List"%>
<%@page import="com.blogspot.bwgypyth.lotro.EMF"%>
<%@page import="javax.persistence.EntityManager"%>
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%
EntityManager em = EMF.get().createEntityManager();
try {
	List<PacketGroup> groups = em.createQuery("select group from PacketGroup group", PacketGroup.class).getResultList();
%>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title></title>
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script type="text/javascript" src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
		<link rel="stylesheet" href="css/file.css">
	</head>
	<body>
		<%@ include file="navigation.jsp" %>
		<h1>Upload new packet</h1>
		<form action="packet_upload" method="post">
			<table>
				<tr>
					<th>Name</th>
					<td><input type="text" name="name" size="50" /></td>
				</tr>
				<tr>
					<th>Group</th>
					<td>
						<select name="group_key" id="group">
<%
	for (PacketGroup group : groups) {
		pageContext.setAttribute("group", group);
%>
							<option value="${group.key}"${group.name == 'Default' ? ' selected="selected"' : ''}>${group.name}</option>
<%
	}
%>
						</select>
						<a onclick="createGroupDialog(); return false;" href="#" class="button">Add group</a>
					</td>
				</tr>
				<tr>
					<th>Data</th>
					<td><textarea rows="10" cols="50" name="data"></textarea></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;"><input type="submit" value="save" /></td>
				</tr>
			</table>
		</form>
		<script type="text/javascript" src="js/group.edit.js"></script>
		<div id="create_group_dialog"></div>
		<script type="text/javascript">$(function() { $('a.button, input[type=submit], input[type=button]').button(); });</script>
	</body>
</html>
<%
} finally {
	em.close();
}
%>

src/main/webapp/packets.jsp
<%@page import="java.util.Comparator"%>
<%@page import="java.util.Collections"%>
<%@page import="java.util.ArrayList"%>
<%@page import="java.util.List"%>
<%@page import="javax.persistence.EntityManager"%>
<%@page import="com.blogspot.bwgypyth.lotro.model.Packet"%>
<%@page import="com.blogspot.bwgypyth.lotro.model.PacketGroup"%>
<%@page import="com.blogspot.bwgypyth.lotro.EMF"%>
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%
EntityManager em = EMF.get().createEntityManager();
try {
	List<Packet> packets;
	if (request.getParameter("group") == null || request.getParameter("group").isEmpty()) {
		packets = em.createQuery("select packet from Packet packet", Packet.class).getResultList();
	} else {
		packets = em.createQuery("select packet from Packet packet where group.key = :groupKey", Packet.class).setParameter("groupKey", Integer.parseInt(request.getParameter("group"))).getResultList();
	}
	Collections.sort(packets, new Comparator<Packet>() {
		public int compare(Packet o1, Packet o2) {
			int compareTo = o1.getGroup().getName().compareTo(o2.getGroup().getName());
			if (compareTo == 0) {
				compareTo = o1.getName().compareTo(o2.getName());
				if (compareTo == 0) {
					compareTo = o1.getKey().compareTo(o2.getKey());
				}
			}
			return compareTo;
		}
	});
%>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Available packets</title>
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script type="text/javascript" src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
		<link rel="stylesheet" href="css/file.css">
		<style type="text/css">
			table {
				border-spacing: 0px;
			}
			td.packetgroup {
				padding-top: 0.5em;
				font-weight: bold;
				padding-left: 0.5em;
				border-bottom: 1px solid #cccccc;
			}
			tr.packetrow:hover td {
				background-color: #aed0ff;
			}
		</style>
	</head>
	<body>
		<%@ include file="navigation.jsp" %>
		<h1>Available packets</h1>
		<table>
			<thead>
				<tr>
					<th>Packet</th>
					<th>No. of analyses</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
<%
PacketGroup group = null;
for (Packet packet : packets) {
	if ((group == null && packet.getGroup() != null) || (group != null && !group.getKey().equals(packet.getGroup().getKey()))) {
		group = packet.getGroup();
		pageContext.setAttribute("group", group);
%>
				<tr>
					<td colspan="3" class="packetgroup"><a href="packets.jsp?group=${group.key}">${group.name}</a> <a style="font-weight: normal;" href="/export/packetgroup?group=${group.key}">Export</a></td>
				</tr>
<%
	}
	pageContext.setAttribute("packet", packet);
%>
				<tr class="packetrow">
					<td><a href="packet.jsp?packet=${packet.key}">${packet.name}</a></td>
					<td>${packet.analysesSize}</td>
					<td><a href="/export/packet?packet=${packet.key}">Export</a> <a href="/export/packet?packet=${packet.key}&amp;type=binary">Export binary</a></td>
				</tr>
<%
}
%>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="3"><a href="packet_upload.jsp" class="button">Upload packet</a> <a href="packet_import.jsp" class="button">Import packet in JSON format</a></td>
				</tr>
			</tfoot>
		</table>
		<script type="text/javascript">$(function() { $('a.button, input[type=submit], input[type=button]').button(); });</script>
	</body>
</html>
<%
} finally {
	em.close();
}
%>